# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='namer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bnamer.proto\"i\n\x0bNameRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\x12\x0e\n\x06suffix\x18\x05 \x01(\t\"!\n\x0cNameResponse\x12\x11\n\tfull_name\x18\x01 \x01(\t29\n\x05Namer\x12\x30\n\x0f\x45nglishFullName\x12\x0c.NameRequest\x1a\r.NameResponse\"\x00\x62\x06proto3')
)




_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='NameRequest.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='NameRequest.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middle_name', full_name='NameRequest.middle_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='NameRequest.prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suffix', full_name='NameRequest.suffix', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=120,
)


_NAMERESPONSE = _descriptor.Descriptor(
  name='NameResponse',
  full_name='NameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_name', full_name='NameResponse.full_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
DESCRIPTOR.message_types_by_name['NameResponse'] = _NAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), dict(
  DESCRIPTOR = _NAMEREQUEST,
  __module__ = 'namer_pb2'
  # @@protoc_insertion_point(class_scope:NameRequest)
  ))
_sym_db.RegisterMessage(NameRequest)

NameResponse = _reflection.GeneratedProtocolMessageType('NameResponse', (_message.Message,), dict(
  DESCRIPTOR = _NAMERESPONSE,
  __module__ = 'namer_pb2'
  # @@protoc_insertion_point(class_scope:NameResponse)
  ))
_sym_db.RegisterMessage(NameResponse)



_NAMER = _descriptor.ServiceDescriptor(
  name='Namer',
  full_name='Namer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=157,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='EnglishFullName',
    full_name='Namer.EnglishFullName',
    index=0,
    containing_service=None,
    input_type=_NAMEREQUEST,
    output_type=_NAMERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAMER)

DESCRIPTOR.services_by_name['Namer'] = _NAMER

# @@protoc_insertion_point(module_scope)
