# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import namer_pb2 as namer__pb2


class NamerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EnglishFullName = channel.unary_unary(
        '/Namer/EnglishFullName',
        request_serializer=namer__pb2.NameRequest.SerializeToString,
        response_deserializer=namer__pb2.NameResponse.FromString,
        )


class NamerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EnglishFullName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NamerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EnglishFullName': grpc.unary_unary_rpc_method_handler(
          servicer.EnglishFullName,
          request_deserializer=namer__pb2.NameRequest.FromString,
          response_serializer=namer__pb2.NameResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Namer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
